---
# Task to disable AppArmor

# Check if AppArmor is running
- name: Check AppArmor status
  ansible.builtin.command: "systemctl is-active apparmor"
  register: apparmor_status
  failed_when: false 
  changed_when: false

- name: Stop AppArmor if it is running
  ansible.builtin.systemd:
    name: apparmor
    state: stopped
  when: apparmor_status.stdout == 'active'

- name: Disable AppArmor to prevent it from starting at boot
  ansible.builtin.systemd:
    name: apparmor
    enabled: no
  when: apparmor_status.stdout == 'active'
  notify: Reboot
